### ISSUE TITLE
Replacement characters in calculator

### ISSUE THREAD

**Issue by za3k** [sbp/saxo#101]
(05:45:21 PM) dpk: .c 10583 * 10583 * 4
(05:45:22 PM) saxo: 10�583 * 10�583 * 4 = 447�999�556
(05:46:25 PM) za3k: Is saxo outputting replacement characters or should i blame pidgin
(05:46:34 PM) dpk: no, i see them too
(05:46:42 PM) dpk: .saxo bug

**Comment by sbp** [comment]
(10:18:30 PM) sbp: kk fixt itxhu
