### ISSUE TITLE
work around pidgin-otr in /msg

### ISSUE THREAD

**Issue by za3k** [sbp/saxo#102]
I wanna avoid spamming. Halp me please

In IRC channel:
> (09:22:16 PM) za3k: .ety janitor
(09:22:19 PM) saxo: "janitor (n.)1580s, 'an usher in a school,' later 'doorkeeper' (1620s), from Latin ianitor 'doorkeeper, porter,' from ianua 'door, entrance, gate,' from ianus 'arched passageway, arcade' (see Janus) + agent suffix -tor. Meaning 'caretaker of a building, man employed to see that rooms are kept clean and in order' first..." - https://www.etymonline.com/word/janitor

In /msg:
> (09:24:45 PM) za3k: .ety janitor
(09:24:47 PM) saxo: Nothing found. Try http://etymonline.com/search.php?term=janitor (No definitions found in https://www.etymonline.com/word/janitor%20%09%20%20%09%09%09%09%20%09%20%09%20%09%20%20%20%20%09%09%20%20%09%20%20%20%09%09%20%20%09%09)

**Comment by za3k** [comment]
Can you strip out trailing whitespace? Pidgin-OTR is screwing it up

**Comment by sbp** [comment]
Done, on our Libera instance. (Haven't changed the code in tree here since it's not actually broken.) Can you please file an issue against Pidgin-OTR, since that's where the actual problem is?

**Comment by za3k** [comment]
nope! they won't fix it.
