### ISSUE TITLE
Misparse on .wik macerate 

### ISSUE THREAD

**Issue by zort** [sbp/saxo#56]
`.wik macerate` returns:

"[Disambiguation] Maceration (food), in food preparation Maceration (wine), a step
       in **wine-making ion,** a wine-making technique Maceration (sewage), in sewage
       treatment" - https://en.wikipedia.org/wiki/Macerate

**Comment by sbp** [comment]
That's what's on the page. What's being misparsed?

**Comment by zort** [comment]
The item "Maceration (wine), a step in wine-making" is being run together with its subitem "Carbonic maceration, a wine-making technique". Instead of saying "Maceration (wine), a step
in wine-making ion, a wine-making technique", saxo should say "Maceration (wine), a step
in wine-making *Carbonic macerat*ion, a wine-making technique".

**Comment by sbp** [comment]
Thanks, fixed in 87f1921.
